import Mathlib
open Polynomial

namespace PadicExamples

/-!
# Examples

A collection of statements about `ℚ_[p]` and `ℤ_[p]`, the `p`-adic numbers and
`p`-adic integers in mathlib.

Try to solve these exercises on paper first, and then write up the proofs here as
an exercise in finding the right library lemmas.
-/

/-- Theruare root of `p` in `ℚ_[p]`. -/
example {p : ℕ} [Fact p.Prime] (x : ℚ_[p]) : x ^ 2 ≠ p := by
  intro h
  have hval : Padic.valuation (x ^ 2) = Padic.valuation (p : ℚ_[p]) := by
    rw [h]
  rw [Padic.valuation_pow, Padic.valuation_p] at hval
  have hnot_div : (2 : ℤ) ∣ 1 := ⟨ Padic.valuation x, hval.symm ⟩
  norm_num at hnot_div

/-- Similarly, there is no square root of `p ^ 3` in `ℚ_[p]`. -/
example {p : ℕ} [Fact p.Prime] (x : ℚ_[p]) : x ^ 2 ≠ (p : ℚ_[p]) ^ 3 := by
  intro h
  have hval : Padic.valuation (x ^ 2) = Padic.valuation (p ^ 3 : ℚ_[p]) := by -- ask whther this is precise enough
    rw [h]
  rw [Padic.valuation_pow, Padic.valuation_pow, Padic.valuation_p] at hval -- repeat as many times as rw is required
  have hnot_div : (2 : ℤ) ∣ 3 := ⟨ Padic.valuation x, hval.symm ⟩
  norm_num at hnot_div -- grind also worked, ask which is a better way to close the goal

/- NOTE FOR SELF (keyword for mathlib theorems): Padic for Q_[p] in mathlib, PadicRat for Q in mathlib,
and PadicInt for Z_[p] in mathlib-/

/-- `p` is not a unit in the `p`-adic integers. -/
example {p : ℕ} [Fact p.Prime] : ¬ IsUnit (p : ℤ_[p]) := by
  rw[PadicInt.isUnit_iff]
  rw[PadicInt.norm_p]
  intro h
  have hp : (1 : ℝ) < p := by
    norm_num
    exact (Fact.out (p := p.Prime)).one_lt
  rw [inv_eq_one] at h
  linarith

/-- The powers of `p` tend to `0` in `ℚ_[p]`. -/

/-
Check mathlib -> filter -> defs
1) tendsto : Filter.Tendsto is the generic "limit of a function" predicate.
Takes in 3 arguments f l₁ l₂ asserts that for every l₂ neighborhood a,
the f-preimage of a is an l₁ neighborhood.

2) atTop : atTop is the filter representing the limit → ∞ on an ordered set.
It is generated by the collection of up-sets {b | a ≤ b}.
For - ∞ use atBot

3) nhds : neighborhoods. A set is called a neighborhood of x if it
contains an open set around x (below x = 0, X = ℚ_[p])
nhds x = ⨅ s ∈ {s : Set X | x ∈ s ∧ IsOpen s}
-/
example {p : ℕ} [Fact p.Prime] : Filter.Tendsto (fun n : ℕ => (p : ℚ_[p]) ^ n)
 Filter.atTop (nhds 0) := by
  apply tendsto_pow_atTop_nhds_zero_of_norm_lt_one -- mention use of Gemini for this
  rw [Padic.norm_p]
  have hp : (1 : ℝ) < p := by
    norm_num
    exact (Fact.out (p := p.Prime)).one_lt
  exact inv_lt_one_of_one_lt₀ hp -- found using try?


local instance : Fact (Nat.Prime 7) := ⟨by norm_num⟩
local instance : Fact (Nat.Prime 3) := ⟨by norm_num⟩

/--`2` has a square root in `ℤ_[7]`.

This is an application of Hensel's lemma. -/
lemma two_not_sq_mod7 : ∃ w : ZMod 7, w ^ 2 = 2 := by decide

example : ∃ z : ℤ_[7], z ^ 2 = 2 := by
  choose w h  using two_not_sq_mod7 --look into the choose / obtain tactic
  -- similar to rintro
  -- look to poly.aeval omit choose w h
  have hred : (PadicInt.toZMod z) ^ 2 = 2 := by -- introducing the reduction map ℤ_[3] → 𝔽_3
  --aim is to show that [z]^2 ≅ 2 (mod 7) in 𝔽_3
    have h := congrArg (PadicInt.toZMod (p := 7)) hz
    rw [map_pow, map_ofNat] at h
    exact h
  exact two_not_sq_mod3 _ hred
  sorry

/-- `2` has no square root in `ℤ_[3]`. -/
lemma two_not_sq_mod3 : ∀ w : ZMod 3, w ^ 2 ≠ 2 := by decide
-- manually calculates all the sq mod3 and deduces that 2 is not a sq in 𝔽_3

example : ¬ ∃ z : ℤ_[3], z ^ 2 = 2 := by
  rintro ⟨z, hz⟩
  have hred : (PadicInt.toZMod z) ^ 2 = 2 := by -- introducing the reduction map ℤ_[3] → 𝔽_3
  --aim is to show that [z]^2 ≅ 2 (mod 3) in 𝔽_3
    have h := congrArg (PadicInt.toZMod (p := 3)) hz
    rw [map_pow, map_ofNat] at h
    exact h
  exact two_not_sq_mod3 _ hred

/-- The geometric series `∑ pⁿ` converges in `ℚ_[p]` to `(1 - p)⁻¹`. Note that this is
false in `ℝ`. -/
example {p : ℕ} [Fact p.Prime] :
∑' n : ℕ, (p : ℚ_[p]) ^ n = (1 - (p : ℚ_[p]))⁻¹ := by
--check mathlib -> limits -> normed for general formula for geometric sum
  apply tsum_geometric_of_norm_lt_one
  rw [Padic.norm_p] -- rewrites using formula for p-adic norm which we need to prove is less than 1
  have hp : (1 : ℝ) < p := by -- padic norm is less than 1 since p > 1
    norm_num
    exact (Fact.out (p := p.Prime)).one_lt -- same used earlier
  rw [inv_lt_one_iff₀]
  right
  exact hp

/-- Every `p`-adic integer is the limit of a sequence of ordinary integers (`ℤ` is dense in
`ℤ_[p]`). -/
example {p : ℕ} [Fact p.Prime] (x : ℤ_[p]) :
    ∃ a : ℕ → ℤ, Filter.Tendsto (fun n => (a n : ℤ_[p])) Filter.atTop (nhds x) := by
  sorry

/-! A weird fact in `p`-adic analysis: a series `∑ f n` converges **iff** its terms tend
to `0`. This is not true in `ℝ` (e.g., the harmonic series). -/
example {p : ℕ} [Fact p.Prime] (f : ℕ → ℚ_[p]) :
    Summable f ↔ Filter.Tendsto f Filter.atTop (nhds 0) := by
  sorry


lemma three_not_sq_mod7 : ∀ w : ZMod 7, w ^ 2 ≠ 3 := by decide
-- z^2 = 3 has no solutions in Z[7]
example : ¬ ∃ z : ℤ_[7], z ^ 2 = 3 := by
  have h7 : Fact (Nat.Prime 7) := ⟨by norm_num⟩ -- record that 7 os a prime
  rintro ⟨z, hz⟩ -- set up a contradicton ∃z in Z[7] s.t z^2 = 3
  have hred : (PadicInt.toZMod z) ^ 2 = 3 := by -- applying the reduction map
    have h := congrArg (PadicInt.toZMod (p := 7)) hz -- applying to both sides
    rw [map_pow, map_ofNat] at h -- ring hom preserves powers and ring hom preserves constants
    exact h
  exact three_not_sq_mod7 _ hred -- contra bs the lemma already computes all the squares mod 7
end PadicExamples
/- DEFINING THE HILBERT SYMBOL
- Take in 3  componenets : p a b

look into the legendre symbol construction
-/
